apiVersion: v1
kind: ConfigMap
metadata:
  name: wrappp-web-config
  namespace: default
  labels:
    app: wrappp-web
data:
  NEXT_PUBLIC_API_BASE: "https://api.wrappp.link"
  NEXT_PUBLIC_REDIRECT_BASE: "https://go.wrappp.link"
  PORT: "8080"
  NODE_ENV: "production"
